### ISSUE TITLE
Failing action with new MAlonzo automation

### ISSUE THREAD

**Issue by WhatisRT** [IntersectMBO/formal-ledger-specifications#542]
I've got this failing action when I pushed a small cosmetic change to a PR & merged it right after:

https://github.com/IntersectMBO/formal-ledger-specifications/actions/runs/10389662769/job/28768205508

It's not a big issue since everything should work, but it'd be nicer if the failure didn't happen. Can you have a look at it @Lucsanszky?

**Comment by WhatisRT** [comment]
Here's another one, this time I didn't merge it before the action finished: https://github.com/IntersectMBO/formal-ledger-specifications/actions/runs/10402995221/job/28808576767?pr=532

**Comment by Lucsanszky** [comment]
So these are caused by missing branches because the related PRs were created and opened before the workflow update. The MAlonzo automation creates the branches for the generated code when you open a PR but since the PR was already open, the branches were not created and thus the failure. You can either just close and re-open the PR and the automation will create and push the branch or you can manually create and push the missing branches (`andre/deregdrep-deposit-amt-MAlonzo` and `andre/pdf-cleanup-MAlonzo`).

**Comment by WhatisRT** [comment]
I see, thanks!
