### ISSUE TITLE
Replace usage of `minUTxOValue` with `coinsPerUTxOByte`

### ISSUE THREAD

**Issue by lehins** [IntersectMBO/formal-ledger-specifications#571]
It was brought up by the audit that current implementation of `paramsWellFormed` is incorrect https://github.com/IntersectMBO/formal-ledger-specifications/blob/2e29cba60e5bbe4bbfa835ba73b976dd993b6bf6/src/Ledger/PParams.lagda#L102-L107

Instead of `minUTxOValue` in it should be using `coinsPerUTxOByte`, because `minUTxOValue` has been removed back in Alonzo era.

The only ticket that I could find ab out this is: https://github.com/IntersectMBO/formal-ledger-specifications/issues/162, which I think should have been taken care of properly and `minUTxOValue` should have been removed. It would have prevented it from being used in the current Conway specification.

Quick repo search also revealed that it `minUTxOValue` is also still used in the `Utxo` rule https://github.com/IntersectMBO/formal-ledger-specifications/blob/76ad4e9ba6ff84d7181d74e5e2dfc797ea45af4e/src/Ledger/Utxo/Haskell.agda#L104 which is also quite wrong

**Comment by WhatisRT** [comment]
Yeah, there's a certain tension between historical stuff and new things. At some point we need to give in and deal with this properly, but it's best to do that as late as possible so that we don't need to duplicate a whole lot of work. And we have arguably more important things to work on still.

In this specific case I think replacing `minUTxOValue` with `coinsPerUTxOByte` everywhere is fine, and I guess we could even remove it. We'll just have to add it back later when we do previous eras.
